# Generated by Django 5.1.3 on 2025-11-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.IntegerField(max_length=3)),
                ('subject', models.TextField(max_length=50)),
                ('material', models.TextField(max_length=100)),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('day', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
    ]
