# Generated by Django 5.1.3 on 2025-11-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='time_studied',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='term',
            field=models.IntegerField(),
        ),
    ]
