# Generated by Django 5.2.8 on 2025-11-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notion', '0002_remove_note_content_note_notes_note_time_studied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='finish_time',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='material',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='start_time',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='time_studied',
            field=models.CharField(default=0),
        ),
    ]
