# Generated by Django 5.2.8 on 2025-11-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notion', '0003_alter_note_date_alter_note_finish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='term',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
